- name: Copy {{ component }} service and dynamically update placeholders
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true